export type Language = "en" | "vi";

export const initialLyricGreeting: Record<Language, string> = {
  en: "Hello! I'm your AI Lyric Assistant. Tell me about the vibe, theme, or some keywords, and I'll help you draft polished lyrics.",
  vi: "Chao ban! Toi la tro ly viet loi bai hat bang AI. Hay noi cho toi biet vibe, chu de, hoac vai tu khoa, toi se giup ban phac thao loi bai hat gon va dep.",
};

export const content = {
  en: {
    nav: {
      home: "Home",
      studio: "Studio",
      music: "Music",
      about: "About",
      journal: "Journal",
      contact: "Reach Us",
      begin: "Begin Journey",
      toggleTheme: "Toggle theme",
      toggleLanguage: "Switch language",
    },
    hero: {
      lead: "Where ",
      accent: "dreams",
      bridge: " rise ",
      end: "through the silence.",
      body:
        "We're designing tools for deep thinkers, bold creators, and quiet rebels. Amid the chaos, we build digital spaces for sharp focus and inspired work.",
      cta: "Begin Journey",
      scroll: "Scroll to explore",
    },
    studio: {
      label: "The Studio",
      titleTop: "Crafting digital",
      titleAccent: "sanctuaries.",
      body:
        "Our studio is a laboratory for the senses. We combine cutting-edge technology with timeless design principles to create interfaces that feel as natural as they are powerful.",
      button: "View Projects",
      card1: "Minimalist Architecture",
      card2: "Fluid Interactions",
    },
    about: {
      label: "Our Philosophy",
      titleTop: "We believe in the",
      titleAccent: "power of focus.",
      body:
        "In a world designed to distract, we build for the moments that matter. BreezeBoy was founded on the idea that technology should disappear into the background, leaving only the clarity of your own thoughts.",
      awards: "Global Awards",
      users: "Active Users",
      latency: "Latency Goal",
    },
    journal: {
      label: "The Journal",
      title: "Latest Insights",
      button: "Read All Entries",
      meta: "Design • April 2024",
      cardTitle: "The psychology of minimalist interfaces in the age of AI.",
    },
    ai: {
      label: "The Lab",
      title: "AI Creative Studio",
      body:
        "Sketch lyrics and browse royalty-free loop ideas from Looperman without leaving the page.",
      beatTitle: "Beat Finder",
      beatMeta: "Looperman Search",
      beatLoading: "Searching matching beats...",
      beatSample:
        '"dark trap bells", "summer afrobeat loop", "sad piano drill", "rnb guitar loop"',
      beatPlaceholder: "Describe the beat or loop you need...",
      beatButton: "Find Beats",
      beatPreviewAlt: "Beat preview",
      beatSourceLabel: "Looperman",
      beatPreviewHint: "Preview stream from source page",
      beatOpenButton: "Open Source",
      beatCopyButton: "Copy link",
      beatCopied: "Link copied",
      beatCopyError: "Could not copy the source link from this browser session.",
      beatEmpty: "Search for a mood, genre, or artist reference to find matching beats.",
      beatNoResults: "No matching beats found. Try broader keywords.",
      beatError: "Failed to search beats. Please try again later.",
      beatDiagnosticTitle: "Diagnostics",
      beatDiagnosticStatus: "Status",
      beatDiagnosticUnknown: "Unknown error",
      beatDiagnosticHint: "Open the source page and use only the downloads or rights provided there.",
      lyricTitle: "Lyric Assistant",
      lyricMeta: "Songwriting Partner",
      lyricPlaceholder: "Ask for lyrics, rhymes, or ideas...",
      lyricDiagnosticTitle: "Diagnostics",
      lyricDiagnosticStatus: "Status",
      lyricDiagnosticUnknown: "Unknown error",
      lyricDiagnosticHint: "Copy this message if you need support.",
      lyricError: "Sorry, I encountered an error while writing lyrics. Please try again.",
      noResponse: "No response",
      lyricFailed: "Failed to generate lyrics",
    },
    contact: {
      label: "Contact",
      titleTop: "Let's start",
      titleAccent: "something.",
      email: "Email",
      studio: "Studio",
      name: "Name",
      emailField: "Email",
      message: "Message",
      projectPlaceholder: "Tell us about your project...",
      send: "Send Message",
    },
    footer: {
      rights: "© 2024 Breeze Boy Studio. All rights reserved.",
    },
  },
  vi: {
    nav: {
      home: "Trang Chu",
      studio: "Studio",
      music: "Nhac",
      about: "Gioi Thieu",
      journal: "Tap Chi",
      contact: "Lien He",
      begin: "Bat Dau",
      toggleTheme: "Chuyen giao dien",
      toggleLanguage: "Chuyen ngon ngu",
    },
    hero: {
      lead: "Noi ",
      accent: "giac mo",
      bridge: " cat canh ",
      end: "giua lang im.",
      body:
        "Chung toi thiet ke cong cu cho nhung nguoi suy nghi sau, nhung nha sang tao tao bao va nhung ke noi loan lang le. Giua hon loan, chung toi tao ra khong gian so cho su tap trung va cam hung.",
      cta: "Bat Dau",
      scroll: "Cuon de kham pha",
    },
    studio: {
      label: "Studio",
      titleTop: "Kien tao nhung khong gian so",
      titleAccent: "an tinh.",
      body:
        "Studio cua chung toi la mot phong thi nghiem cho giac quan. Chung toi ket hop cong nghe hien dai voi nguyen ly thiet ke vuot thoi gian de tao ra giao dien tu nhien va day suc manh.",
      button: "Xem Du An",
      card1: "Kien Truc Toi Gian",
      card2: "Tuong Tac Mem Mai",
    },
    about: {
      label: "Triet Ly",
      titleTop: "Chung toi tin vao",
      titleAccent: "suc manh cua su tap trung.",
      body:
        "Trong mot the gioi duoc tao ra de gay xao nhang, chung toi xay dung cho nhung khoanh khac thuc su quan trong. BreezeBoy duoc sinh ra tu niem tin rang cong nghe nen lui vao hau canh, chi de lai su ro rang trong suy nghi cua ban.",
      awards: "Giai Thuong Toan Cau",
      users: "Nguoi Dung Hoat Dong",
      latency: "Muc Tieu Do Tre",
    },
    journal: {
      label: "Tap Chi",
      title: "Goc Nhin Moi",
      button: "Doc Tat Ca",
      meta: "Thiet ke • Thang 4 2024",
      cardTitle: "Tam ly hoc cua giao dien toi gian trong ky nguyen AI.",
    },
    ai: {
      label: "Phong Lab",
      title: "AI Creative Studio",
      body:
        "Phac thao lyric va tim loop/beat tham khao tu Looperman ngay trong trang nay.",
      beatTitle: "Tim Beat",
      beatMeta: "Tim Tren Looperman",
      beatLoading: "Dang tim beat phu hop...",
      beatSample:
        '"dark trap bells", "summer afrobeat loop", "sad piano drill", "rnb guitar loop"',
      beatPlaceholder: "Mo ta beat hoac loop ban can...",
      beatButton: "Tim Beat",
      beatPreviewAlt: "Nghe thu beat",
      beatSourceLabel: "Looperman",
      beatPreviewHint: "Nghe thu tu trang nguon",
      beatOpenButton: "Mo nguon",
      beatCopyButton: "Copy link",
      beatCopied: "Da sao chep link",
      beatCopyError: "Khong the sao chep link nguon trong phien trinh duyet nay.",
      beatEmpty: "Hay tim theo mood, the loai hoac nghe si tham chieu de lay beat phu hop.",
      beatNoResults: "Khong tim thay beat phu hop. Thu tu khoa rong hon.",
      beatError: "Khong the tim beat luc nay. Vui long thu lai sau.",
      beatDiagnosticTitle: "Chan Doan",
      beatDiagnosticStatus: "Ma loi",
      beatDiagnosticUnknown: "Loi khong xac dinh",
      beatDiagnosticHint: "Hay mo trang nguon va chi dung cac quyen tai/xu ly duoc cap o do.",
      lyricTitle: "Tro Ly Loi Nhac",
      lyricMeta: "Ban dong hanh sang tac",
      lyricPlaceholder: "Hoi ve loi bai hat, van, hoac y tuong...",
      lyricDiagnosticTitle: "Chan Doan",
      lyricDiagnosticStatus: "Ma loi",
      lyricDiagnosticUnknown: "Loi khong xac dinh",
      lyricDiagnosticHint: "Hay gui thong diep nay neu ban can kiem tra tiep.",
      lyricError: "Xin loi, da co loi khi viet loi bai hat. Vui long thu lai.",
      noResponse: "Khong co phan hoi",
      lyricFailed: "Khong the tao loi bai hat",
    },
    contact: {
      label: "Lien He",
      titleTop: "Cung bat dau",
      titleAccent: "mot dieu gi do.",
      email: "Email",
      studio: "Studio",
      name: "Ten",
      emailField: "Email",
      message: "Tin Nhan",
      projectPlaceholder: "Hay ke cho chung toi ve du an cua ban...",
      send: "Gui Tin Nhan",
    },
    footer: {
      rights: "© 2024 Breeze Boy Studio. Da dang ky moi quyen.",
    },
  },
} as const;
